# Generated by Django 4.2.2 on 2023-06-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_filetemplate_active_alter_show_duration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetemplate',
            name='ignore_fields',
            field=models.ManyToManyField(null=True, related_name='ignored', to='core.namesmatch'),
        ),
    ]
