# Generated by Django 4.2.2 on 2023-06-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_filetemplate_ignore_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetemplate',
            name='ignore_fields',
            field=models.ManyToManyField(blank=True, null=True, related_name='ignored', to='core.namesmatch'),
        ),
    ]
